//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASBOOK
    {
        public Nullable<System.DateTime> DT { get; set; }
        public string TM { get; set; }
        public string CLASNM { get; set; }
        public string TEACHER { get; set; }
        public string RMNO { get; set; }
        public string JOINER { get; set; }
        public int MANS { get; set; }
        public string RMTAG { get; set; }
        public string TAGID { get; set; }
        public string RSTA { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string LOGUSR { get; set; }
    }
}
