//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRAA
    {
        public string CNANO { get; set; }
        public Nullable<short> RNTP { get; set; }
        public Nullable<short> RNTERTP { get; set; }
        public string DEALERNM { get; set; }
        public Nullable<System.DateTime> DT1 { get; set; }
        public Nullable<System.DateTime> DT2 { get; set; }
        public Nullable<short> YRS { get; set; }
        public Nullable<short> MNS { get; set; }
        public Nullable<short> DYS { get; set; }
        public Nullable<int> RNFEE { get; set; }
        public Nullable<short> RNFEETP { get; set; }
        public string NOTES { get; set; }
        public string JOBTAG { get; set; }
        public string CNSTA { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public string TAGID { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string LOGUSR { get; set; }
        public string OTHERN { get; set; }
        public string ENDYM { get; set; }
        public short ENDDAYS { get; set; }
        public Nullable<decimal> DSCON1 { get; set; }
        public Nullable<decimal> DSCON2 { get; set; }
    }
}
