//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESKCASH
    {
        public short INOUT { get; set; }
        public short AMTTP { get; set; }
        public int AMT { get; set; }
        public string CHKNO { get; set; }
        public string RMNO { get; set; }
        public string MAN { get; set; }
        public string INTP { get; set; }
        public string NOTES { get; set; }
        public string LOGUSR { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string RSTA { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public string TAGID { get; set; }
        public short PAYTP { get; set; }
    }
}
