//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEFORM
    {
        public string RMNO { get; set; }
        public string FEETP { get; set; }
        public string RMTAG { get; set; }
        public Nullable<short> YR { get; set; }
        public Nullable<System.DateTime> FDT1 { get; set; }
        public Nullable<System.DateTime> FDT2 { get; set; }
        public short DSCON1 { get; set; }
        public short DSCON2 { get; set; }
        public Nullable<System.DateTime> TUNEDT { get; set; }
        public Nullable<decimal> TUNEUP { get; set; }
        public Nullable<int> FEEAMT { get; set; }
        public string TAGID { get; set; }
        public string CNNO { get; set; }
        public Nullable<decimal> UPY4 { get; set; }
        public Nullable<decimal> UPY2 { get; set; }
        public Nullable<decimal> UPY3 { get; set; }
        public Nullable<decimal> UPY5 { get; set; }
    }
}
