//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOMEAST
    {
        public string CNM { get; set; }
        public string SEX { get; set; }
        public string COUNTRY { get; set; }
        public string PID { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string WORKITEM { get; set; }
        public string WORKWITH { get; set; }
        public string WORKNOTE { get; set; }
        public string TAGID { get; set; }
    }
}
