//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYFEE
    {
        public string RMNO { get; set; }
        public string MAN { get; set; }
        public string FEETP { get; set; }
        public string FEEYM { get; set; }
        public int FEEAMT { get; set; }
        public int PAYAMT { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string LOGUSR { get; set; }
        public string OTHERN { get; set; }
        public string TAGID { get; set; }
        public string FEEFROM { get; set; }
        public string FEETAG { get; set; }
        public string RMTAG { get; set; }
        public string RSTA { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
    }
}
