//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAST
    {
        public string ASST { get; set; }
        public string CNTRY { get; set; }
        public Nullable<System.DateTime> CIDT { get; set; }
        public Nullable<System.DateTime> CODT { get; set; }
        public Nullable<int> WORKTP { get; set; }
        public string NOTES { get; set; }
        public string RSTA { get; set; }
        public string JOBTAG { get; set; }
        public string TAGID { get; set; }
    }
}
