//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMBUDGET
    {
        public string YRN { get; set; }
        public Nullable<decimal> M01 { get; set; }
        public Nullable<decimal> M02 { get; set; }
        public Nullable<decimal> M03 { get; set; }
        public Nullable<decimal> M04 { get; set; }
        public Nullable<decimal> M05 { get; set; }
        public Nullable<decimal> M06 { get; set; }
        public Nullable<decimal> M07 { get; set; }
        public Nullable<decimal> M08 { get; set; }
        public Nullable<decimal> M09 { get; set; }
        public Nullable<decimal> M10 { get; set; }
        public Nullable<decimal> M11 { get; set; }
        public Nullable<decimal> M12 { get; set; }
        public string TAGID { get; set; }
    }
}
