//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMFEEM
    {
        public string RMNO { get; set; }
        public string RMTAG { get; set; }
        public string FEETP { get; set; }
        public string FEEYM { get; set; }
        public int FEEAMT { get; set; }
        public int AMTTX { get; set; }
        public int AMTSUM { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public Nullable<System.DateTime> FEEDT1 { get; set; }
        public Nullable<System.DateTime> FEEDT2 { get; set; }
        public short YMDAYS { get; set; }
        public string TAGID { get; set; }
        public string CNNO { get; set; }
        public int PAYAMT { get; set; }
        public string RSTA { get; set; }
        public short CNDAYS { get; set; }
        public string ENDYM { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public short DSDAYS { get; set; }
    }
}
