//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMLIV
    {
        public string MAN { get; set; }
        public string SEX { get; set; }
        public string CNTRY { get; set; }
        public string BLOD { get; set; }
        public string BLODTP { get; set; }
        public string APPES { get; set; }
        public Nullable<System.DateTime> CIDT { get; set; }
        public Nullable<System.DateTime> CODT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public string PID { get; set; }
        public string POSL { get; set; }
        public int MARRI { get; set; }
        public string NOTES { get; set; }
        public string JOBTAG { get; set; }
        public string RSTA { get; set; }
        public string TAGID { get; set; }
        public string EMAILPW { get; set; }
    }
}
