//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMF
    {
        public string CNO { get; set; }
        public decimal PINS { get; set; }
        public string ADR1 { get; set; }
        public string DOOR { get; set; }
        public string FLOR { get; set; }
        public Nullable<decimal> PINS0 { get; set; }
        public Nullable<decimal> PRCN { get; set; }
        public string EXTNO { get; set; }
        public string LOCT { get; set; }
        public string STY { get; set; }
        public string PICNM { get; set; }
        public string IP1 { get; set; }
        public string IP2 { get; set; }
        public short ONUSE { get; set; }
        public string WATERNO { get; set; }
        public string ELECNO { get; set; }
        public string GASNO { get; set; }
    }
}
