//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTCONF
    {
        public int GUID { get; set; }
        public string EITEM1 { get; set; }
        public string EITEM2 { get; set; }
        public string EITEM3 { get; set; }
        public string EITEM4 { get; set; }
        public string EITEM5 { get; set; }
        public string EITEM6 { get; set; }
        public string CITEM1 { get; set; }
        public string CITEM2 { get; set; }
        public string CITEM3 { get; set; }
        public string CITEM4 { get; set; }
        public string CITEM5 { get; set; }
        public string CITEM6 { get; set; }
        public string KIND { get; set; }
    }
}
