//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CNHIN
    {
        public string CNHNO { get; set; }
        public string RMNO { get; set; }
        public Nullable<short> CSTTP { get; set; }
        public string DEALERNM { get; set; }
        public string DEALMAN { get; set; }
        public string COMETP { get; set; }
        public string COMENOTE { get; set; }
        public string MLIVER { get; set; }
        public string BROKERNM { get; set; }
        public string BROKMAN { get; set; }
        public int BROKFEE { get; set; }
        public System.DateTime DT1 { get; set; }
        public System.DateTime DT2 { get; set; }
        public Nullable<short> YRS { get; set; }
        public Nullable<short> MNS { get; set; }
        public Nullable<short> DYS { get; set; }
        public Nullable<int> RNFEE { get; set; }
        public Nullable<short> RNFEETP { get; set; }
        public Nullable<int> MGFEE { get; set; }
        public Nullable<short> MGFEETP { get; set; }
        public Nullable<int> GUAFEE { get; set; }
        public string CNHNOTE { get; set; }
        public string LOGUSR { get; set; }
        public string TAGID { get; set; }
        public string CNSTA { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string DEALNO { get; set; }
        public string BROKNO { get; set; }
        public string ENDYM { get; set; }
        public short ENDDAYS { get; set; }
        public short SP { get; set; }
        public Nullable<decimal> DSCON1 { get; set; }
        public Nullable<decimal> DSCON2 { get; set; }
    }
}
