//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DEALER
    {
        public string CNO { get; set; }
        public string CNM { get; set; }
        public string ENM { get; set; }
        public string RUNTP { get; set; }
        public Nullable<int> CSTTP { get; set; }
        public string COMETP { get; set; }
        public Nullable<int> CSTLEVL { get; set; }
        public string CPID { get; set; }
        public string CPMGR { get; set; }
        public string CPADR { get; set; }
        public string SENDADR { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CNHNO { get; set; }
        public string RMNO { get; set; }
        public string TAGID { get; set; }
        public string CNSTA { get; set; }
        public Nullable<int> RNFEE { get; set; }
        public Nullable<int> MGFEE { get; set; }
        public System.DateTime DT1 { get; set; }
        public System.DateTime DT2 { get; set; }
    }
}
