//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RPT513
    {
        public long RID { get; set; }
        public string RMTXT { get; set; }
        public decimal PINS { get; set; }
        public string MAN { get; set; }
        public string DEALERNM { get; set; }
        public string MANME { get; set; }
        public string DT1 { get; set; }
        public string DT2 { get; set; }
        public string CNTRY { get; set; }
        public string TEL_M { get; set; }
        public string TEL_O { get; set; }
        public string TEL_D { get; set; }
        public string TEL_S { get; set; }
    }
}
