//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RPT524
    {
        public string TAGID { get; set; }
        public string RMNO { get; set; }
        public string DEALERNM { get; set; }
        public string FEEYM { get; set; }
        public string CPID { get; set; }
        public Nullable<int> AMTSUM { get; set; }
        public string MLIVER { get; set; }
        public string RMTXT { get; set; }
        public Nullable<int> RPT31 { get; set; }
        public Nullable<int> RPT32 { get; set; }
        public Nullable<int> RPT33 { get; set; }
        public Nullable<int> RPT34 { get; set; }
        public Nullable<int> RPT35 { get; set; }
        public Nullable<int> RPT36 { get; set; }
        public Nullable<int> RPT37 { get; set; }
        public Nullable<int> RPT38 { get; set; }
        public Nullable<int> RPT39 { get; set; }
        public Nullable<int> RPT40 { get; set; }
        public Nullable<int> RPT41 { get; set; }
        public Nullable<int> RPT42 { get; set; }
        public Nullable<int> RPT45 { get; set; }
        public Nullable<int> RPTSUM { get; set; }
    }
}
