//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RPT502
    {
        public string TAGID { get; set; }
        public string RMNO { get; set; }
        public string DEALERNM { get; set; }
        public string FEEYM { get; set; }
        public string CPID { get; set; }
        public Nullable<int> AMTSUM { get; set; }
        public string MLIVER { get; set; }
        public string RMTXT { get; set; }
        public Nullable<int> RPT1 { get; set; }
        public Nullable<int> RPT2 { get; set; }
        public Nullable<int> RPT3 { get; set; }
        public Nullable<int> RPT4 { get; set; }
        public Nullable<int> RPT5 { get; set; }
        public Nullable<int> RPT6 { get; set; }
        public Nullable<int> RPT7 { get; set; }
        public Nullable<int> RPT8 { get; set; }
        public Nullable<int> RPTSUM { get; set; }
    }
}
