//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RPT515
    {
        public long RID { get; set; }
        public string RMTXT { get; set; }
        public string CTYPE { get; set; }
        public string CNPNO { get; set; }
        public Nullable<short> RNTP { get; set; }
        public Nullable<int> PARKNO { get; set; }
        public Nullable<System.DateTime> DT1 { get; set; }
        public Nullable<System.DateTime> DT2 { get; set; }
        public string ENDYM { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public string RMNO { get; set; }
        public string DEALERNM { get; set; }
        public string TPNM { get; set; }
        public string EYY { get; set; }
        public string EYM { get; set; }
    }
}
