//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WATERFEE
    {
        public string FEEYM { get; set; }
        public int AMTSUM { get; set; }
        public string ADR { get; set; }
        public string WATRNO { get; set; }
        public int DGRES1 { get; set; }
        public int DGRES2 { get; set; }
        public int DGRESN { get; set; }
        public Nullable<System.DateTime> FEEDT1 { get; set; }
        public Nullable<System.DateTime> FEEDT2 { get; set; }
        public Nullable<System.DateTime> LOGDT { get; set; }
        public string LOGUSR { get; set; }
        public string TAGID { get; set; }
        public string RSTA { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
    }
}
