//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IntranetSystem.Models
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class FDPOSEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'FDPOSEntities' 區段中找到的連接字串，初始化新的 FDPOSEntities 物件。
        /// </summary>
        public FDPOSEntities() : base("name=FDPOSEntities", "FDPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FDPOSEntities 物件。
        /// </summary>
        public FDPOSEntities(string connectionString) : base(connectionString, "FDPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FDPOSEntities 物件。
        /// </summary>
        public FDPOSEntities(EntityConnection connection) : base(connection, "FDPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<FDPOST01> FDPOST01
        {
            get
            {
                if ((_FDPOST01 == null))
                {
                    _FDPOST01 = base.CreateObjectSet<FDPOST01>("FDPOST01");
                }
                return _FDPOST01;
            }
        }
        private ObjectSet<FDPOST01> _FDPOST01;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 FDPOST01 EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToFDPOST01(FDPOST01 fDPOST01)
        {
            base.AddObject("FDPOST01", fDPOST01);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FDPOSModel", Name="FDPOST01")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FDPOST01 : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 FDPOST01 物件。
        /// </summary>
        /// <param name="pOSNO">POSNO 屬性的初始值。</param>
        /// <param name="pOSPNO">POSPNO 屬性的初始值。</param>
        public static FDPOST01 CreateFDPOST01(global::System.String pOSNO, global::System.String pOSPNO)
        {
            FDPOST01 fDPOST01 = new FDPOST01();
            fDPOST01.POSNO = pOSNO;
            fDPOST01.POSPNO = pOSPNO;
            return fDPOST01;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POSNO
        {
            get
            {
                return _POSNO;
            }
            set
            {
                if (_POSNO != value)
                {
                    OnPOSNOChanging(value);
                    ReportPropertyChanging("POSNO");
                    _POSNO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("POSNO");
                    OnPOSNOChanged();
                }
            }
        }
        private global::System.String _POSNO;
        partial void OnPOSNOChanging(global::System.String value);
        partial void OnPOSNOChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POSPNO
        {
            get
            {
                return _POSPNO;
            }
            set
            {
                if (_POSPNO != value)
                {
                    OnPOSPNOChanging(value);
                    ReportPropertyChanging("POSPNO");
                    _POSPNO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("POSPNO");
                    OnPOSPNOChanged();
                }
            }
        }
        private global::System.String _POSPNO;
        partial void OnPOSPNOChanging(global::System.String value);
        partial void OnPOSPNOChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POSPNM
        {
            get
            {
                return _POSPNM;
            }
            set
            {
                OnPOSPNMChanging(value);
                ReportPropertyChanging("POSPNM");
                _POSPNM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POSPNM");
                OnPOSPNMChanged();
            }
        }
        private global::System.String _POSPNM;
        partial void OnPOSPNMChanging(global::System.String value);
        partial void OnPOSPNMChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PRICE
        {
            get
            {
                return _PRICE;
            }
            set
            {
                OnPRICEChanging(value);
                ReportPropertyChanging("PRICE");
                _PRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRICE");
                OnPRICEChanged();
            }
        }
        private Nullable<global::System.Int32> _PRICE;
        partial void OnPRICEChanging(Nullable<global::System.Int32> value);
        partial void OnPRICEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DUTYFREE
        {
            get
            {
                return _DUTYFREE;
            }
            set
            {
                OnDUTYFREEChanging(value);
                ReportPropertyChanging("DUTYFREE");
                _DUTYFREE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DUTYFREE");
                OnDUTYFREEChanged();
            }
        }
        private global::System.String _DUTYFREE;
        partial void OnDUTYFREEChanging(global::System.String value);
        partial void OnDUTYFREEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIB
        {
            get
            {
                return _ATTRIB;
            }
            set
            {
                OnATTRIBChanging(value);
                ReportPropertyChanging("ATTRIB");
                _ATTRIB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIB");
                OnATTRIBChanged();
            }
        }
        private global::System.String _ATTRIB;
        partial void OnATTRIBChanging(global::System.String value);
        partial void OnATTRIBChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> COST
        {
            get
            {
                return _COST;
            }
            set
            {
                OnCOSTChanging(value);
                ReportPropertyChanging("COST");
                _COST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COST");
                OnCOSTChanged();
            }
        }
        private Nullable<global::System.Decimal> _COST;
        partial void OnCOSTChanging(Nullable<global::System.Decimal> value);
        partial void OnCOSTChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> COST_RATE
        {
            get
            {
                return _COST_RATE;
            }
            set
            {
                OnCOST_RATEChanging(value);
                ReportPropertyChanging("COST_RATE");
                _COST_RATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COST_RATE");
                OnCOST_RATEChanged();
            }
        }
        private Nullable<global::System.Decimal> _COST_RATE;
        partial void OnCOST_RATEChanging(Nullable<global::System.Decimal> value);
        partial void OnCOST_RATEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENAME
        {
            get
            {
                return _ENAME;
            }
            set
            {
                OnENAMEChanging(value);
                ReportPropertyChanging("ENAME");
                _ENAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENAME");
                OnENAMEChanged();
            }
        }
        private global::System.String _ENAME;
        partial void OnENAMEChanging(global::System.String value);
        partial void OnENAMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> POUND
        {
            get
            {
                return _POUND;
            }
            set
            {
                OnPOUNDChanging(value);
                ReportPropertyChanging("POUND");
                _POUND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POUND");
                OnPOUNDChanged();
            }
        }
        private Nullable<global::System.Decimal> _POUND;
        partial void OnPOUNDChanging(Nullable<global::System.Decimal> value);
        partial void OnPOUNDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REMARK
        {
            get
            {
                return _REMARK;
            }
            set
            {
                OnREMARKChanging(value);
                ReportPropertyChanging("REMARK");
                _REMARK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REMARK");
                OnREMARKChanged();
            }
        }
        private global::System.String _REMARK;
        partial void OnREMARKChanging(global::System.String value);
        partial void OnREMARKChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MENUATR
        {
            get
            {
                return _MENUATR;
            }
            set
            {
                OnMENUATRChanging(value);
                ReportPropertyChanging("MENUATR");
                _MENUATR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MENUATR");
                OnMENUATRChanged();
            }
        }
        private global::System.String _MENUATR;
        partial void OnMENUATRChanging(global::System.String value);
        partial void OnMENUATRChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SALE
        {
            get
            {
                return _SALE;
            }
            set
            {
                OnSALEChanging(value);
                ReportPropertyChanging("SALE");
                _SALE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SALE");
                OnSALEChanged();
            }
        }
        private global::System.String _SALE;
        partial void OnSALEChanging(global::System.String value);
        partial void OnSALEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOURCE
        {
            get
            {
                return _SOURCE;
            }
            set
            {
                OnSOURCEChanging(value);
                ReportPropertyChanging("SOURCE");
                _SOURCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOURCE");
                OnSOURCEChanged();
            }
        }
        private global::System.String _SOURCE;
        partial void OnSOURCEChanging(global::System.String value);
        partial void OnSOURCEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRINO
        {
            get
            {
                return _PRINO;
            }
            set
            {
                OnPRINOChanging(value);
                ReportPropertyChanging("PRINO");
                _PRINO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRINO");
                OnPRINOChanged();
            }
        }
        private global::System.String _PRINO;
        partial void OnPRINOChanging(global::System.String value);
        partial void OnPRINOChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLASSID
        {
            get
            {
                return _CLASSID;
            }
            set
            {
                OnCLASSIDChanging(value);
                ReportPropertyChanging("CLASSID");
                _CLASSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLASSID");
                OnCLASSIDChanged();
            }
        }
        private global::System.String _CLASSID;
        partial void OnCLASSIDChanging(global::System.String value);
        partial void OnCLASSIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PACKAGE
        {
            get
            {
                return _PACKAGE;
            }
            set
            {
                OnPACKAGEChanging(value);
                ReportPropertyChanging("PACKAGE");
                _PACKAGE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PACKAGE");
                OnPACKAGEChanged();
            }
        }
        private global::System.String _PACKAGE;
        partial void OnPACKAGEChanging(global::System.String value);
        partial void OnPACKAGEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STOP
        {
            get
            {
                return _STOP;
            }
            set
            {
                OnSTOPChanging(value);
                ReportPropertyChanging("STOP");
                _STOP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STOP");
                OnSTOPChanged();
            }
        }
        private global::System.String _STOP;
        partial void OnSTOPChanging(global::System.String value);
        partial void OnSTOPChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> QTY
        {
            get
            {
                return _QTY;
            }
            set
            {
                OnQTYChanging(value);
                ReportPropertyChanging("QTY");
                _QTY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QTY");
                OnQTYChanged();
            }
        }
        private Nullable<global::System.Decimal> _QTY;
        partial void OnQTYChanging(Nullable<global::System.Decimal> value);
        partial void OnQTYChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NOWQTY
        {
            get
            {
                return _NOWQTY;
            }
            set
            {
                OnNOWQTYChanging(value);
                ReportPropertyChanging("NOWQTY");
                _NOWQTY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NOWQTY");
                OnNOWQTYChanged();
            }
        }
        private Nullable<global::System.Decimal> _NOWQTY;
        partial void OnNOWQTYChanging(Nullable<global::System.Decimal> value);
        partial void OnNOWQTYChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KPOSPNM
        {
            get
            {
                return _KPOSPNM;
            }
            set
            {
                OnKPOSPNMChanging(value);
                ReportPropertyChanging("KPOSPNM");
                _KPOSPNM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KPOSPNM");
                OnKPOSPNMChanged();
            }
        }
        private global::System.String _KPOSPNM;
        partial void OnKPOSPNMChanging(global::System.String value);
        partial void OnKPOSPNMChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UDATE
        {
            get
            {
                return _UDATE;
            }
            set
            {
                OnUDATEChanging(value);
                ReportPropertyChanging("UDATE");
                _UDATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UDATE");
                OnUDATEChanged();
            }
        }
        private global::System.String _UDATE;
        partial void OnUDATEChanging(global::System.String value);
        partial void OnUDATEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MENUCHK
        {
            get
            {
                return _MENUCHK;
            }
            set
            {
                OnMENUCHKChanging(value);
                ReportPropertyChanging("MENUCHK");
                _MENUCHK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MENUCHK");
                OnMENUCHKChanged();
            }
        }
        private global::System.String _MENUCHK;
        partial void OnMENUCHKChanging(global::System.String value);
        partial void OnMENUCHKChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CASE_CHARGE
        {
            get
            {
                return _CASE_CHARGE;
            }
            set
            {
                OnCASE_CHARGEChanging(value);
                ReportPropertyChanging("CASE_CHARGE");
                _CASE_CHARGE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CASE_CHARGE");
                OnCASE_CHARGEChanged();
            }
        }
        private global::System.String _CASE_CHARGE;
        partial void OnCASE_CHARGEChanging(global::System.String value);
        partial void OnCASE_CHARGEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SEQ
        {
            get
            {
                return _SEQ;
            }
            set
            {
                OnSEQChanging(value);
                ReportPropertyChanging("SEQ");
                _SEQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SEQ");
                OnSEQChanged();
            }
        }
        private Nullable<global::System.Decimal> _SEQ;
        partial void OnSEQChanging(Nullable<global::System.Decimal> value);
        partial void OnSEQChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLASSID_BAK
        {
            get
            {
                return _CLASSID_BAK;
            }
            set
            {
                OnCLASSID_BAKChanging(value);
                ReportPropertyChanging("CLASSID_BAK");
                _CLASSID_BAK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLASSID_BAK");
                OnCLASSID_BAKChanged();
            }
        }
        private global::System.String _CLASSID_BAK;
        partial void OnCLASSID_BAKChanging(global::System.String value);
        partial void OnCLASSID_BAKChanged();

        #endregion

    
    }

    #endregion

    
}
